/**
 * POST /api/admin/announcements — broadcast a notification to all users
 * GET  /api/admin/announcements — recent broadcasts, newest first
 *
 * Mounted behind requireAuth + requireAdmin.
 *
 * An announcement is stored as a SINGLE row with user_id = NULL rather than
 * fanned out per account. Announcing to 100k users is therefore one insert,
 * and per-user read state still works because reads live in their own table
 * (see migration 006).
 *
 * This is kept separate from the automatic new-content notifications on
 * purpose: those are generated by notify_new_content() as a side effect of
 * publishing, while these are composed by a human and are the only kind an
 * admin can create directly.
 */

import { Router } from 'express'
import { supabase } from '../db/supabaseClient.js'
import { requireAuth, requireAdmin } from '../middleware/auth.js'

const router = Router()

router.use(requireAuth, requireAdmin)

const MAX_TITLE = 200
const MAX_MESSAGE = 2000

/**
 * Only site-relative links are accepted. An admin-composed notification is
 * shown to every user, so allowing an absolute URL would turn this into an
 * open redirect surface pointed at the whole userbase.
 */
export function normaliseLink(raw) {
  if (raw === undefined || raw === null || raw === '') return { ok: true, value: null }
  if (typeof raw !== 'string') return { ok: false }

  const link = raw.trim()
  if (!link.startsWith('/') || link.startsWith('//')) return { ok: false }
  return { ok: true, value: link }
}

// ── POST /api/admin/announcements ────────────────────────────────────────────
router.post('/', async (req, res) => {
  const { title, message, link, thumbnail, segmentLanguage } = req.body ?? {}

  if (typeof title !== 'string' || title.trim().length === 0) {
    return res.status(400).json({ error: 'Title is required.' })
  }
  if (title.trim().length > MAX_TITLE) {
    return res.status(400).json({ error: `Title must be ${MAX_TITLE} characters or fewer.` })
  }
  if (message != null && typeof message !== 'string') {
    return res.status(400).json({ error: 'Message must be text.' })
  }
  if (typeof message === 'string' && message.length > MAX_MESSAGE) {
    return res.status(400).json({ error: `Message must be ${MAX_MESSAGE} characters or fewer.` })
  }

  const linkResult = normaliseLink(link)
  if (!linkResult.ok) {
    return res.status(400).json({ error: 'Link must be a site-relative path starting with "/".' })
  }

  const thumbResult = normaliseThumbnail(thumbnail)
  if (!thumbResult.ok) {
    return res.status(400).json({ error: 'Thumbnail must be an https:// URL or a site-relative path.' })
  }

  const { data, error } = await supabase
    .from('notifications')
    .insert({
      user_id: null, // broadcast
      type: 'announcement',
      title: title.trim(),
      message: typeof message === 'string' && message.trim() ? message.trim() : null,
      link: linkResult.value,
      thumbnail: thumbResult.value,
      segment_language:
        typeof segmentLanguage === 'string' && segmentLanguage.trim() ? segmentLanguage.trim() : null,
    })
    .select('id, title, message, link, thumbnail, segment_language, created_at')
    .single()

  if (error) {
    console.error('[admin/announcements]', error.message)
    return res.status(500).json({ error: 'Could not send announcement.' })
  }

  res.status(201).json({ announcement: data })
})

// ── GET /api/admin/announcements ─────────────────────────────────────────────
router.get('/', async (req, res) => {
  const { data, error } = await supabase
    .from('notifications')
    .select('id, title, message, link, thumbnail, segment_language, created_at')
    .is('user_id', null)
    .eq('type', 'announcement')
    .order('created_at', { ascending: false })
    .limit(25)

  if (error) {
    console.error('[admin/announcements:list]', error.message)
    return res.status(500).json({ error: 'Could not load announcements.' })
  }

  res.json({ announcements: data ?? [] })
})

/**
 * Thumbnails may be absolute (the CDN) or site-relative (a bundled asset), but
 * never javascript:/data: — those would execute in the notification list.
 */
export function normaliseThumbnail(raw) {
  if (raw === undefined || raw === null || raw === '') return { ok: true, value: null }
  if (typeof raw !== 'string') return { ok: false }

  const value = raw.trim()
  if (value.startsWith('/') && !value.startsWith('//')) return { ok: true, value }
  if (/^https:\/\/[^\s]+$/i.test(value)) return { ok: true, value }
  return { ok: false }
}

export default router
